# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

raw_output = ""
user_token = ""

[filter]
  limit = ""
  offset = ""
  topic = ""

[remotes]
  bootstrap_url = "http://localhost:9013"
  certs_url = "http://localhost:9019"
  http_adapter_url = "http://localhost/http:9016"
  reader_url = "http://localhost:9011"
  clients_url = "http://localhost:9006"
  tls_verification = false
  users_url = "http://localhost:9002"
  channels_url = "http://localhost:9005"
  groups_url = "http://localhost:9004"
  domains_url = "http://localhost:9003"
