# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          always-auth: false
          check-latest: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Jest tests
        run: npm test -- --passWithNoTests

      - name: Lint with ESLint
        run: pnpm run lint
